mkdir bloodstream
sox bloodstream.wav bloodstream/bloodstreamsplit_0.wav trim 0 10
sox bloodstream.wav bloodstream/bloodstreamsplit_1.wav trim 10 10
sox bloodstream.wav bloodstream/bloodstreamsplit_2.wav trim 20 10
sox bloodstream.wav bloodstream/bloodstreamsplit_3.wav trim 30 10
sox bloodstream.wav bloodstream/bloodstreamsplit_4.wav trim 40 10
sox bloodstream.wav bloodstream/bloodstreamsplit_5.wav trim 50 10
sox bloodstream.wav bloodstream/bloodstreamsplit_6.wav trim 60 10
sox bloodstream.wav bloodstream/bloodstreamsplit_7.wav trim 70 10
sox bloodstream.wav bloodstream/bloodstreamsplit_8.wav trim 80 10
sox bloodstream.wav bloodstream/bloodstreamsplit_9.wav trim 90 10
sox bloodstream.wav bloodstream/bloodstreamsplit_10.wav trim 100 10
sox bloodstream.wav bloodstream/bloodstreamsplit_11.wav trim 110 10
sox bloodstream.wav bloodstream/bloodstreamsplit_12.wav trim 120 10
sox bloodstream.wav bloodstream/bloodstreamsplit_13.wav trim 130 10
sox bloodstream.wav bloodstream/bloodstreamsplit_14.wav trim 140 10
sox bloodstream.wav bloodstream/bloodstreamsplit_15.wav trim 150 10
sox bloodstream.wav bloodstream/bloodstreamsplit_16.wav trim 160 10
sox bloodstream.wav bloodstream/bloodstreamsplit_17.wav trim 170 10
sox bloodstream.wav bloodstream/bloodstreamsplit_18.wav trim 180 10
sox bloodstream.wav bloodstream/bloodstreamsplit_19.wav trim 190 10
sox bloodstream.wav bloodstream/bloodstreamsplit_20.wav trim 200 10
sox bloodstream.wav bloodstream/bloodstreamsplit_21.wav trim 210 10
